config/routes.rb
Rails.application.routes.draw do
  resources :tweets

  root to: "tweets#index"

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  def strip_text
    text = EngTagger.new
                    .get_readable(self.text)
                    .split(" ")
                    .map { |tagged_words| tagged_words.split("/") }
                    .reject { |_, tag| tag == "JJ"  ||
                                       tag == "RB"  ||
                                       tag == "RBR" ||
                                       tag == "RBS" ||
                                       tag == "RP" }
                    .map { |word, _| word }
    acc = []

    text.each do |t|
      unless [".", ",", "?", "!"].include?(t)
        acc << t
      else
        last = acc.pop
        acc << (last + t)
      end
    end

    acc.join(" ")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:text)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
  def redact(tagged)
    text = tagged.split(" ")
                 .map { |tagged_words| tagged_words.split("/") }
                 .map { |word, tag|
                        unless tag == "JJ"  ||
                               tag == "RB"  ||
                               tag == "RBR" ||
                               tag == "RBS" ||
                               tag == "RP"
                          word
                        else
                          "<span style=\"background-color:black;color:black\">#{word}</span>"
                        end}
    reduce(text, [])
  end

  def strip(tagged)
    text = tagged.split(" ")
                 .map { |tagged_words| tagged_words.split("/") }
                 .reject { |_, tag| tag == "JJ"  ||
                                    tag == "RB"  ||
                                    tag == "RBR" ||
                                    tag == "RBS" ||
                                    tag == "RP" }
                 .map { |word, _| word }

    reduce(text, [])
  end

  private

  def reduce(text, acc)
    acc = []

    text.each do |t|
      unless [".", ",", "?", "!"].include?(t)
        acc << t
      else
        last = acc.pop
        acc << (last + t)
      end
    end

    acc.join(" ").html_safe
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NoAdjectives</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tweets/_form.html.erb
<%= form_for(@tweet) do |f| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% @tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form' %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>@realDonaldTrump's No-Adjective Tweets</h1>
<br>
<% @tweets.each do |tweet| %>
  <h3><%= tweet.created_at %></h3>
  <ul>
    <li style="list-style:none"><h4>Raw</h4></li>
    <ul>
      <li style="list-style:none;"><%= tweet.text %></li>
    </ul>
  </ul>
  <ul>
    <li style="list-style:none"><h4>Redacted</h4></li>
    <ul>
      <li style="list-style:none"><%= redact(tweet.pos_tagged_text) %></li>
    </ul>
  </ul>
  <ul>
    <li style="list-style:none"><h4>Stripped</h4></li>
    <ul>
      <li style="list-style:none" ><%= strip(tweet.pos_tagged_text) %></li>
    </ul>
  </ul>
  <br>
<% end %>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form' %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @tweet.text %>
</p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>